services:
  telegram-vacation-night-bot:
    build: .
    container_name: telegram_vacation_night_bot_container
    environment:
      - TZ=Europe/Rome
    restart: unless-stopped

    volumes:
      - ./data/logs:/code/app/logs
      - ./data/session:/code/app/session

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
